[workspace]
members = [
    "buildpacks/noop-a",
    "buildpacks/noop-b",
    "buildpacks/noop-multi-arch"
]
resolver = "2"

[workspace.package]
version = "0.0.1"
rust-version = "1.66"
edition = "2021"
publish = false

[workspace.dependencies]
libcnb = "0.11"