api = "0.8"

[buildpack]
id = "org/noop-multi-arch"
version = "0.1.8"
name = "(multi-arch) - Noop Buildpack"
description = "(multi-arch) - A buildpack that does nothing"

[[stacks]]
id = "some-target-stack"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/noop/noop-multi-arch"

[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"