api = "0.8"

[buildpack]
id = "noop-a"
version = "0.0.2"
name = "(a) - Noop Buildpack"
description = "(a) - A buildpack that does nothing"

[[stacks]]
id = "some-target-stack"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/noop/noop-a"