api = "0.8"

[buildpack]
id = "org/noop-a"
version = "0.1.5"
name = "(a) - Noop Buildpack"
description = "(a) - A buildpack that does nothing"

[[stacks]]
id = "some-target-stack"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/noop/noop-a"
