api = "0.8"

[buildpack]
id = "noop-b"
version = "0.0.7"
name = "(b) - Noop Buildpack"
description = "(b) - A buildpack that does nothing"

[[stacks]]
id = "some-target-stack"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/noop/noop-b"