api = "0.8"

[buildpack]
id = "org/noop-b"
version = "0.1.3"
name = "(b) - Noop Buildpack"
description = "(b) - A buildpack that does nothing"

[[stacks]]
id = "*"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/noop/noop-b"
