api = "0.8"

[buildpack]
id = "org/noop-meta"
version = "0.1.3"
name = "Noop Meta Buildpack"
description = "A meta buildpack that does nothing"

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "org/noop-a"
version = "0.1.3"

[[order.group]]
id = "org/noop-b"
version = "0.1.3"

[[order.group]]
id = "org/noop-bash"
version = "0.1.3"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/noop/noop-meta"
