api = "0.8"

[buildpack]
id = "noop-meta"
version = "0.0.2"
name = "Noop Meta Buildpack"
description = "A meta buildpack that does nothing"

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "noop-a"
version = "0.0.1"

[[order.group]]
id = "noop-b"
version = "0.0.1"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/noop/noop-meta"