name: PR Trigger Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  info:
    if: (github.event.pull_request && github.event.pull_request.merged) || true
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "HEAD REF:  ${{ github.head_ref }}"
          echo "PR TITLE:  ${{ github.event.pull_request.title }}"
          echo "PR MERGED: ${{ github.event.pull_request.merged }}"
      - name: talkback
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Released the buildpack!" --repo ${{ github.repository }}