name: Prepare Buildpack (Shared Action)

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump"
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bump Versions and Update Changelogs
        id: prepare
        uses: colincasey/languages-github-actions/.github/actions/prepare-release@main
        with:
          bump: ${{ inputs.bump }}
      - name: Generate Changelog
        id: generate-changelog
        uses: colincasey/languages-github-actions/.github/actions/generate-changelog@main
        with:
          version: ${{ steps.prepare.outputs.to_version }}
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          title: Prepare release v${{ steps.prepare.outputs.to_version }}
          commit-message: Prepare release v${{ steps.prepare.outputs.to_version }}
          branch: release/v${{ steps.prepare.outputs.to_version }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          labels: "automation"
      - name: Configure PR
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}