name: Prepare Buildpack Releases

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump"
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  prepare-release:
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-prepare-release.yml@main
    with:
      bump: ${{ inputs.bump }}
      app_id: ${{ vars.LINGUIST_GH_APP_ID }}
      declarations_starting_version: 1.0.0
      ip_allowlisted_runner: ubuntu-latest
    secrets:
      app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}