name: Prepare Buildpack

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump"
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - id: list
        run: ls .
      - id: prepare
        uses: colincasey/languages-github-actions/.github/actions/prepare-release@main
        with:
          bump: ${{ inputs.bump }}
      - name: Check output
        run: |
          echo "From:"
          echo ${{ steps.prepare.outputs.from_version }}
          echo "To:"
          echo ${{ steps.prepare.outputs.to_version }}