name: Release (Shared)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  detect:
    name: Detecting Buildpacks
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release-detect.yml@main

  package:
    name: Package / ${{ matrix.id }}
    needs: [ detect ]
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release-package.yml@main
    with:
      buildpack_id: ${{ matrix.id }}
      buildpack_path: ${{ matrix.path }}