name: Release Buildpacks

on:
  workflow_dispatch:

env:
  dry_run: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release.yml@main
    with:
      app_id: ${{ vars.LINGUIST_GH_APP_ID }}
      dry_run: true
      ip_allowlisted_runner: ubuntu-latest
    secrets:
      app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}
      cnb_registry_token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
