name: Release Buildpack

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump what?"
        required: true
        default: 'Patch'
        type: choice
        options:
          - Major
          - Minor
          - Patch

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install musl-tools
        run: sudo apt-get install musl-tools --no-install-recommends
      - name: Update Rust toolchain
        run: rustup update
      - name: Install Rust linux-musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.1
      # Build
      - name: Compile the buildpack
        run: cargo libcnb package --release