name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  detect:
    name: Detecting Buildpacks
    runs-on: ubuntu-latest
    outputs:
      buildpacks: ${{ steps.generate-buildpack-matrix.outputs.buildpacks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Buildpack Matrix
        id: generate-buildpack-matrix
        uses: colincasey/languages-github-actions/.github/actions/generate-buildpack-matrix@main

  package:
    needs: [detect]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    name: Package / ${{ matrix.id }}
    steps:
      # Package
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install musl-tools
        run: sudo apt-get install musl-tools --no-install-recommends
      - name: Update Rust toolchain
        run: rustup update
      - name: Install Rust linux-musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.2.0
      - name: Install yj
        uses: buildpacks/github-actions/setup-tools@v5.2.0
      - name: Install libcnb-cargo
        run: cargo install --git https://github.com/heroku/libcnb.rs --branch ccasey-malax-pairing libcnb-cargo
      - name: Package Buildpack
        id: libcnb-package
        working-directory: ${{ matrix.path }}
        run: echo "dir=$(cargo libcnb package --release)" >> $GITHUB_OUTPUT
      - name: Create CNB File
        working-directory: ${{ steps.libcnb-package.outputs.dir }}
        run: pack buildpack package ${{ matrix.id }}.cnb --config ${{ steps.libcnb-package.outputs.dir }}/package.toml --format file -v
      - name: Create Docker Image
        working-directory: ${{ steps.libcnb-package.outputs.dir }}
        run: pack buildpack package ${{ matrix.id }} --config ${{ steps.libcnb-package.outputs.dir }}/package.toml --config package.toml -v
      - name: Save Docker Image
        run: docker save ${{ matrix.id }} | zstd -T0 --long=31 -o ${{ matrix.id }}.tar.zst
      - name: Save Buildpack Variables
        run: |
          export METADATA=./${{ matrix.id }}.vars
          echo "version=$(yj -t < ${{ matrix.path }}/buildpack.toml | jq -r .buildpack.version)" >> $METADATA
          echo "repository=$(yj -t < ${{ matrix.path }}/buildpack.toml | jq -r .metadata.release.docker.repository)" >> $METADATA
          cat $METADATA
      - name: Cache Outputs
        uses: actions/cache/save@v3
        with:
          key: ${{ github.run_id }}-${{ matrix.id }}
          path: |
            ${{ matrix.id }}.cnb
            ${{ matrix.id }}.tar.zst
            ${{ matrix.id }}.vars

  publish-docker:
    name: Publish / Docker / ${{ matrix.id }}
    needs: [ detect, package ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    steps:
      - name: Restore Docker images from the cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ github.run_id}}-${{ matrix.id }}
          path: |
            ${{ matrix.id }}.cnb
            ${{ matrix.id }}.tar.zst
            ${{ matrix.id }}.vars
      - name: Load Buildpack Variables
        id: buildpack
        run: cat ${{ matrix.id }}.vars >> $GITHUB_OUTPUT
      - name: Check version is unique on Docker Hub
        run: |
          if docker manifest inspect "${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }}" > /dev/null; then
            echo "Duplicate version found on Docker Hub ${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }}"
            exit 1
          fi
      - name: Load Docker images into the Docker daemon
        run: zstd -dc --long=31 ${{ matrix.id }}.tar.zst | docker load
#      - name: Log into Docker Hub
#        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
#      - name: Tag buildpack and push to registries
#        run: |
#          docker tag ${{ matrix.id }} ${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }}
#          docker push ${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }}

  publish-github:
    name: Publish / GitHub / ${{ matrix.id }}
    needs: [ detect, package ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    steps:
      - name: Restore Docker images from the cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ github.run_id}}-${{ matrix.id }}
          path: |
            ${{ matrix.id }}.cnb
            ${{ matrix.id }}.vars
      - name: Load Buildpack Variables
        id: buildpack
        run: cat ${{ matrix.id }}.vars >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.buildpack.outputs.version }}
          release_name: v${{ steps.buildpack.outputs.version }}
          body: |
            See the [CHANGELOG](./CHANGELOG.md) for details.
          draft: true

  publish-cnb:
    name: Publish / CNB Registry / ${{ matrix.id }}
    needs: [ detect, publish-docker ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    steps:
      - name: Install crane
        uses: buildpacks/github-actions/setup-tools@v5.2.0
      - name: Restore Docker images from the cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ github.run_id}}-${{ matrix.id }}
          path: |
            ${{ matrix.id }}.vars
      - name: Load Buildpack Variables
        id: buildpack
        run: cat ${{ matrix.id }}.vars >> $GITHUB_OUTPUT
#      - name: Calculate the buildpack image digest
#        id: digest
#        run: echo "value=$(crane digest ${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }})" >> "$GITHUB_OUTPUT"
#      - name: Register the new version with the CNB Buildpack Registry
#        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.0.1
#        with:
#          token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}
#          id: ${{ matrix.id }}
#          version: ${{ steps.buildpack.outputs.version }}
#          address: ${{ steps.buildpack.outputs.repository }}@${{ steps.digest.outputs.value }}

  update-builder:
    name: Update Builder / ${{ matrix.id }}
    needs: [ detect, publish-docker ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    steps:
      - name: Install crane
        uses: buildpacks/github-actions/setup-tools@v5.2.0
      - name: Restore Docker images from the cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ github.run_id}}-${{ matrix.id }}
          path: |
            ${{ matrix.id }}.vars
      - name: Load Buildpack Variables
        id: buildpack
        run: cat ${{ matrix.id }}.vars >> $GITHUB_OUTPUT
#      - name: Calculate the buildpack image digest
#        id: digest
#        run: echo "value=$(crane digest ${{ steps.buildpack.outputs.repository }}:${{ steps.buildpack.outputs.version }})" >> "$GITHUB_OUTPUT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: heroku/builder
          path: ./builder
      - name: Update Builder
        uses: colincasey/languages-github-actions/.github/actions/update-builder@main
        with:
          path: ./builder
          buildpack-id: ${{ matrix.id }}
          buildpack-version: ${{ steps.buildpack.outputs.version }}
          buildpack-uri: ${{ steps.buildpack.outputs.repository }}@${{ steps.digest.outputs.value }}
          builders: "builder-22,buildpacks-20,builder-classic-22"
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          path: ./builder
#          delete-branch: true
#          branch: update/${{ github.repository }}
