name: Release Buildpacks (shorter)

on:
  workflow_dispatch:

env:
  dry_run: true

permissions:
  contents: write

jobs:
  detect:
    name: Detecting Buildpacks
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release-detect.yml@main

  publish:
    name: Publish
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release-publish-all.yml@main
    needs: [detect]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    with:
      buildpack_id: ${{ matrix.buildpack_id }}
      buildpack_dir: ${{ matrix.buildpack_dir }}
      buildpack_version: ${{ matrix.buildpack_version }}
      buildpack_artifact_prefix: ${{ matrix.buildpack_artifact_prefix }}
      docker_repository: ${{ matrix.docker_repository }}
    secrets:
      cnb_registry_token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  update-builder:
    name: Update Builder
    needs: [detect, publish]
    uses: colincasey/languages-github-actions/.github/workflows/_buildpacks-release-update-builder.yml@main
    with:
      app_id: ${{ vars.LINGUIST_GH_APP_ID }}
      buildpack_version: ${{ needs.detect.outputs.version }}
      dry_run: true
    secrets:
      app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}